### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by JosefJezek** [krmax44/ShowcaseView.js#1]
Could you remove dependency on jQuery and Materialize?
- http://youmightnotneedjquery.com
- https://github.com/oneuijs/You-Dont-Need-jQuery

**Comment by krmax44** [comment]
I'm sorry, but jQuery will always be needed, because it soon will be an jQuery plugin. I plan to remove Materialize in the near future, since it's only needed for the button!
